import { envSchema, type EnvConfig } from "./env.schema";

function readEnv(): EnvConfig {
  return envSchema.parse({
    NODE_ENV: process.env.NODE_ENV,
    LOG_LEVEL: process.env.LOG_LEVEL,
    DATABASE_URL: process.env.DATABASE_URL,
    API_PORT: process.env.API_PORT ?? process.env.PORT,
    WEB_ORIGIN: process.env.WEB_ORIGIN,
    MARKETING_ORIGIN: process.env.MARKETING_ORIGIN,
    JWT_SECRET: process.env.JWT_SECRET,
    JWT_ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN,
    AUTH_ACCESS_COOKIE_MAX_AGE_MS: process.env.AUTH_ACCESS_COOKIE_MAX_AGE_MS,
    REFRESH_TOKEN_EXPIRES_IN_DAYS: process.env.REFRESH_TOKEN_EXPIRES_IN_DAYS,
    AUTH_REFRESH_COOKIE_MAX_AGE_MS: process.env.AUTH_REFRESH_COOKIE_MAX_AGE_MS,
    AUTH_COOKIE_DOMAIN: process.env.AUTH_COOKIE_DOMAIN,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_CALLBACK_URL: process.env.GOOGLE_CALLBACK_URL,
    DEV_AUTH_EMAIL: process.env.DEV_AUTH_EMAIL,
    SWAGGER_ENABLED: process.env.SWAGGER_ENABLED,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    EMAIL_FROM: process.env.EMAIL_FROM,
    REDIS_URL: process.env.REDIS_URL,
    REDIS_KEY_PREFIX: process.env.REDIS_KEY_PREFIX,
    EMAIL_OTP_EXPIRES_MINUTES: process.env.EMAIL_OTP_EXPIRES_MINUTES,
    EMAIL_OTP_RESEND_COOLDOWN_SECONDS: process.env.EMAIL_OTP_RESEND_COOLDOWN_SECONDS,
    EMAIL_OTP_MAX_ATTEMPTS: process.env.EMAIL_OTP_MAX_ATTEMPTS,
    EMAIL_OTP_IP_MAX_REQUESTS: process.env.EMAIL_OTP_IP_MAX_REQUESTS,
    EMAIL_OTP_IP_WINDOW_SECONDS: process.env.EMAIL_OTP_IP_WINDOW_SECONDS,
    EMAIL_OTP_HMAC_SECRET: process.env.EMAIL_OTP_HMAC_SECRET,
    ENABLED_FEATURES: process.env.ENABLED_FEATURES,
    TOGETHER_API_KEY: process.env.TOGETHER_API_KEY,
    TOGETHER_MODEL: process.env.TOGETHER_MODEL,
    TAVILY_API_KEY: process.env.TAVILY_API_KEY,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    R2_BUCKET: process.env.R2_BUCKET,
    R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL,
  });
}

export const appConfig = () => {
  const env = readEnv();

  return {
    nodeEnv: env.NODE_ENV,
    logLevel: env.LOG_LEVEL,
    databaseUrl: env.DATABASE_URL,
    apiPort: env.API_PORT,
    webOrigin: env.WEB_ORIGIN,
    marketingOrigin: env.MARKETING_ORIGIN,
    webOrigins: [env.WEB_ORIGIN, env.MARKETING_ORIGIN],
    jwtSecret: env.JWT_SECRET,
    jwtAccessExpiresIn: env.JWT_ACCESS_EXPIRES_IN,
    authAccessCookieMaxAgeMs: env.AUTH_ACCESS_COOKIE_MAX_AGE_MS,
    refreshTokenExpiresInDays: env.REFRESH_TOKEN_EXPIRES_IN_DAYS,
    authRefreshCookieMaxAgeMs: env.AUTH_REFRESH_COOKIE_MAX_AGE_MS,
    authCookieDomain: env.AUTH_COOKIE_DOMAIN,
    googleClientId: env.GOOGLE_CLIENT_ID,
    googleClientSecret: env.GOOGLE_CLIENT_SECRET,
    googleCallbackUrl: env.GOOGLE_CALLBACK_URL,
    devAuthEmail: env.DEV_AUTH_EMAIL,
    swaggerEnabled: env.NODE_ENV === "production" ? env.SWAGGER_ENABLED : true,
    resendApiKey: env.RESEND_API_KEY,
    emailFrom: env.EMAIL_FROM,
    redisUrl: env.REDIS_URL,
    redisKeyPrefix: env.REDIS_KEY_PREFIX,
    emailOtpExpiresMinutes: env.EMAIL_OTP_EXPIRES_MINUTES,
    emailOtpResendCooldownSeconds: env.EMAIL_OTP_RESEND_COOLDOWN_SECONDS,
    emailOtpMaxAttempts: env.EMAIL_OTP_MAX_ATTEMPTS,
    emailOtpIpMaxRequests: env.EMAIL_OTP_IP_MAX_REQUESTS,
    emailOtpIpWindowSeconds: env.EMAIL_OTP_IP_WINDOW_SECONDS,
    emailOtpHmacSecret: env.EMAIL_OTP_HMAC_SECRET ?? env.JWT_SECRET,
    enabledFeatures: env.ENABLED_FEATURES,
    togetherApiKey: env.TOGETHER_API_KEY,
    togetherModel: env.TOGETHER_MODEL,
    tavilyApiKey: env.TAVILY_API_KEY,
    r2AccountId: env.R2_ACCOUNT_ID,
    r2AccessKeyId: env.R2_ACCESS_KEY_ID,
    r2SecretAccessKey: env.R2_SECRET_ACCESS_KEY,
    r2Bucket: env.R2_BUCKET,
    r2PublicBaseUrl: env.R2_PUBLIC_BASE_URL,
  };
};

export type AppConfig = ReturnType<typeof appConfig>;
